export interface Product {
  name: string
  category: string
  brand: string
  image: string
  code: string
}

export const products: Product[] = [
  { name: "Condutor Vence Tudo - Vence Tudo - 90003691 / 900100091", brand: "Vence Tudo", category: "Condutor", code: "90003691 / 900100091", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-1/1.png" },
  { name: "Condutor - Semeato - 61070014", brand: "Semeato", category: "Condutor", code: "61070014", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-2/1.png" },
  { name: "Condutor Semeato - Semeato - 70080006", brand: "Semeato", category: "Condutor", code: "70080006", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-3/1.png" },
  { name: "Condutor Semeato - Semeato - 56020072", brand: "Semeato", category: "Condutor", code: "56020072", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-4/1.png" },
  { name: "Condutor de Semente - Semeato - 28460049", brand: "Semeato", category: "Condutor", code: "28460049", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-5/1.png" },
  { name: "Condutor Semeato - Semeato - 15070025", brand: "Semeato", category: "Condutor", code: "15070025", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-6/1.png" },
  { name: "Condutor Semeato - Semeato - 15070010", brand: "Semeato", category: "Condutor", code: "15070010", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-7/1.png" },
  { name: "Condutor de Semente - Massey / Valtra / Sfil - 900100374", brand: "Massey", category: "Condutor", code: "900100374", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-8/1.png" },
  { name: "Condutor Longo - Imasa - 50000000556", brand: "Imasa", category: "Condutor", code: "50000000556", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-9/1.png" },
  { name: "Condutor de Adubo - Jumil - 2718303", brand: "Jumil", category: "Condutor", code: "2718303", image: "" },
  { name: "Condutor Curvo - Semeato - 37090001", brand: "Semeato", category: "Condutor", code: "37090001", image: "" },
  { name: "Condutor Curvo Longo - Semeato - 70300006", brand: "Semeato", category: "Condutor", code: "70300006", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-12/1.png" },
  { name: "Batente da Caixa de Semente - Semeato", brand: "Semeato", category: "Batente", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-13/1.png" },
  { name: "Base Boca Dianteira Menor - Semeato - 26100020", brand: "Semeato", category: "Base", code: "26100020", image: "" },
  { name: "Telescópio 5 Estágios - Semeato - (Branco / Transparente) - 15075601", brand: "Semeato", category: "Telescópio", code: "15075601", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-15/1.png" },
  { name: "Telescópio 4 Estágios - Semeato - Branco / Preto / Transparente - 25075701", brand: "Semeato", category: "Telescópio", code: "25075701", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-16/1.png" },
  { name: "Telescópio 4 Estágios - Imasa", brand: "Imasa", category: "Telescópio", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-17/1.png" },
  { name: "Telescópio 4 Estágios - Plant Center", brand: "Plant Center", category: "Telescópio", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-18/1.png" },
  { name: "Telescópio 3 Estágios - Vence Tudo - 900100567", brand: "Vence Tudo", category: "Telescópio", code: "900100567", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-19/1.png" },
  { name: "Telescópio 3 Estágios - Semeato - (Branco / Preto / Transparente) - 25075702", brand: "Semeato", category: "Telescópio", code: "25075702", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-20/1.png" },
  { name: "Telescópio 3 Estágios - Imasa", brand: "Imasa", category: "Telescópio", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-21/1.png" },
  { name: "Telescópio 3 Estágios - Gihal", brand: "Gihal", category: "Telescópio", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-22/1.png" },
  { name: "Telescópio 2 Estágios - Branco / Transparente  - Semeato - 25075703", brand: "Semeato", category: "Telescópio", code: "25075703", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-23/1.png" },
  { name: "Telescópio 2 Estágios - Gihal - Transparente", brand: "Gihal", category: "Telescópio", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-24/1.png" },
  { name: "Volante - 25090029", brand: "", category: "Voltante", code: "25090029", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-26/1.png" },
  { name: "Tampa Isoladora de Adubo - Semeato - 25080015", brand: "Semeato", category: "Tampa", code: "25080015", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-27/1.png" },
  { name: "Tampa do mancal - Semeato - 35200028", brand: "Semeato", category: "Tampa", code: "35200028", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-28/1.png" },
  { name: "Tampa do Cubo Max - 221917", brand: "", category: "Tampa", code: "221917", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-29/1.png" },
  { name: "Rolete/Roldana Esticador Menor - 58060014", brand: "", category: "Rolete", code: "58060014", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-30/1.png" },
  { name: "Rolete/Roldana Esticador Menor - 56040027", brand: "", category: "Rolete", code: "56040027", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-31/1.png" },
  { name: "Rolete/Roldana 22mm - 56040079", brand: "", category: "Rolete", code: "56040079", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-32/1.png" },
  { name: "Pinhão Dosador - 03090045", brand: "", category: "Pinhão Dosador", code: "03090045", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-33/1.png" },
  { name: "Pinhão Conduzido coroa - 03090034", brand: "", category: "Pinhão Conduzido/Coroa", code: "03090034", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-34/1.png" },
  { name: "Obstacularizador Vedador da Caixa de Semente - Semeato - 15090057", brand: "Semeato", category: "Obstacularizador", code: "15090057", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-35/1.png" },
  { name: "Manopla Rosca 10mm", brand: "", category: "Manopla", code: "10mm", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-36/1.png" },
  { name: "Manopla Rosca 8mm", brand: "", category: "Manopla", code: "8mm", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-37/1.png" },
  { name: "Manopla Rosca 6mm", brand: "", category: "Manopla", code: "6mm", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-38/1.png" },
  { name: "Lingueta do Facão - Semeato - 26150003", brand: "Semeato", category: "Lingueta", code: "26150003", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-39/1.png" },
  { name: "Condutor de Sementes - Semeato - 351200013", brand: "Semeato", category: "Condutor", code: "351200013", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-40/1.png" },
  { name: "Condutor de Sementes - Semeato - 72070036 - 76070051 - 33080009", brand: "Semeato", category: "Condutor", code: "33080009", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-41/1.png" },
  { name: "Condutor de Sementes - Semeato - 56020071", brand: "Semeato", category: "Condutor", code: "56020071", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-42/1.png" },
  { name: "Condutor de Sementes - Semeato 26100002", brand: "Semeato", category: "Condutor", code: "26100002", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-43/1.png" },
  { name: "Condutor de Sementes - Semeato - 25070091", brand: "Semeato", category: "Condutor", code: "25070091", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-44/1.png" },
  { name: "Condutor de Adubo Reto - AGCO- Massey - Valtra - 33070004", brand: "AGCO", category: "Condutor", code: "33070004", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-45/1.png" },
  { name: "Condutor de Adubo - Semeato - 26100003", brand: "Semeato", category: "Condutor", code: "26100003", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-46/1.png" },
  { name: "Condutor de Adubo - Semeato - 15070027", brand: "Semeato", category: "Condutor", code: "15070027", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-47/1.png" },
  { name: "Bocal do Condutor - Semeato - 56020062", brand: "Semeato", category: "Bocal", code: "56020062", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-48/1.png" },
  { name: "Dosador de Adubo Completo Universal Direito - Rosca 1'", brand: "", category: "Dosador", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-49/1.png" },
  { name: "Dosador de Adubo Completo Universal Esquerda - Rosca 1'", brand: "", category: "Dosador", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-50/1.png" },
  { name: "Revestimento Meia Lua Direita - Semeato - DI02010003", brand: "Semeato", category: "Revestimento", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-51/1.png" },
  { name: "Telescópio 5 estágios - Semeato - Transparente - 15075601", brand: "Semeato", category: "Telescópio", code: "15075601", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-52/1.png" },
  { name: "Telescópio 2 estágios - Semeato - Branco / Transparente - 36168801", brand: "Semeato", category: "Telescópio", code: "36168801", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-53/1.png" },
  { name: "Mancal Dosador 2 Rolamentos - Universal - 25080024", brand: "", category: "Mancal", code: "25080024", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-54/1.png" },
  { name: "Mancal Dosador 1 Rolamentos - Universal - 25080024", brand: "", category: "Mancal", code: "25080024", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-55/1.png" },
  { name: "Interrupitor Saída da Semente - Semeato - 15090012", brand: "Semeato", category: "Interruptor", code: "15090012", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-56/1.png" },
  { name: "Calço - Kuhn - YC075601", brand: "Semeato", category: "Calota", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-57/1.png" },
  { name: "Flange Acoplador - Semeato - 28180080", brand: "Semeato", category: "Flange", code: "28180080", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-58/1.png" },
  { name: "Fixador Borboleta - 25010087", brand: "", category: "Fixador", code: "25010087", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-59/1.png" },
  { name: "Cubo do Disco Duplo - Linha Sfil - 20070013", brand: "SFIL", category: "Flange", code: "20070013", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-60/1.png" },
  { name: "Condutor Imasa 50700000172", brand: "Imasa", category: "Condutor", code: "50700000172", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-61/1.png" },
  { name: "Chaveta Imasa - 50000000342", brand: "Imasa", category: "Chaveta", code: "50000000342", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-62/1.png" },
  { name: "Calota do Cubo - 25070041", brand: "", category: "Calota", code: "25070041", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-63/1.png" },
  { name: "Calota - 70300020", brand: "", category: "Calota", code: "70300020", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-64/1.png" },
  { name: "Bocal Menor - Semeato - 06070040", brand: "Semeato", category: "Bocal", code: "06070040", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-65/1.png" },
  { name: "Bocal Superior - Semeato - 06070041", brand: "Semeato", category: "Bocal", code: "06070041", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-66/1.png" },
  { name: "Bocal Superior - Semeato - 56020073", brand: "Semeato", category: "Bocal", code: "56020073", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-67/1.png" },
  { name: "Base do Bocal - Semeato - 62010059", brand: "Semeato", category: "Base", code: "62010059", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-68/1.png" },
  { name: "Base do Bocal Traseiro - Semeato - 26100019", brand: "Semeato", category: "Base", code: "26100019", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-69/1.png" },
  { name: "Bocal Superior Menor - Semeato - 56020060", brand: "Semeato", category: "Bocal", code: "56020060", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-76/1.png" },
  { name: "Tubo Caixa de Adubo Revestimento - John Deere - CQ62329", brand: "", category: "Revestimento", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-77/1.png" },
  { name: "Revestimento Meia Lua esquerda - Semeato - DI02010004", brand: "Semeato", category: "Revestimento", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-78/1.png" },
  { name: "Revestimento Meia Lua Direita - Semeato - 06070076", brand: "Semeato", category: "Revestimento", code: "06070076", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-79/1.png" },
  { name: "Revestimento Dosador - Semeato - DI02010002", brand: "Semeato", category: "Revestimento", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-80/1.png" },
  { name: "Revestimento Meia Lua Esquerda - 06070077", brand: "Semeato", category: "Revestimento", code: "06070077", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-81/1.png" },
  { name: "Revestimento Dosador - Semeato - 6070060", brand: "Semeato", category: "Revestimento", code: "6070060", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-82/1.png" },
  { name: "Bocal Inferior Reto  - Semeato - 56020066", brand: "Semeato", category: "Bocal", code: "56020066", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-83/1.png" },
  { name: "Revestimento Tatu Marchesan - 511013789", brand: "Tatu Marchesan", category: "Revestimento", code: "511013789", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-84/1.png" },
  { name: "Bucha Menor do Dosador - Semeato - 06070043", brand: "Semeato", category: "Bucha", code: "06070043", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-85/1.png" },
  { name: "Mangote Telescópio - Semeato - 56020063", brand: "Semeato", category: "Mangote", code: "56020063", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-86/1.png" },
  { name: "Bucha Calotinha - Semeato - 06070069", brand: "Semeato", category: "Bucha", code: "06070069", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-87/1.png" },
  { name: "Bucha Lisa - Semeato - 06070042", brand: "Semeato", category: "Bucha", code: "06070042", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-88/1.png" },
  { name: "Engrenagem 6-Z - Semeato - 35050005", brand: "Semeato", category: "Engrenagem", code: "35050005", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-89/1.png" },
  { name: "Bocal Bifurcado - Semeato - 56200008", brand: "Semeato", category: "Bocal", code: "56200008", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-90/1.png" },
  { name: "Bocal Superior Menor - Semeato - 56020061", brand: "Semeato", category: "Bocal", code: "56020061", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-91/1.png" },
  { name: "Mangote 4 Orelhas - 36120003", brand: "Semeato", category: "Mangote", code: "36120003", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-92/1.png" },
  { name: "Rolete Esticador - Semeato - 03030107", brand: "Semeato", category: "Rolete", code: "03030107", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-93/1.png" },
  { name: "Condutor Universal - 239169", brand: "", category: "Condutor", code: "239169", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-94/1.png" },
  { name: "Condutor de Sementes - Semeato -25070092", brand: "Semeato", category: "Condutor", code: "25070092", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-95/1.png" },
  { name: "Condutor de Adubo - Tatu - 0503030483", brand: "Tatu Marchesan", category: "Condutor", code: "0503030483", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-96/1.png" },
  { name: "Condutor Curto - Case - 0066001235", brand: "Case", category: "Condutor", code: "0066001235", image: "" },
  { name: "Dosador de Adubo Completo Universal (Esquerda) - 2'", brand: "", category: "Dosador", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-98/1.png" },
  { name: "Dosador de Adubo Completo Universal (Direito) - 2'", brand: "", category: "Dosador", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-99/1.png" },
  { name: "Condutor de Adubo - Vence Tudo - 90003604 - 900100249 - 900100070", brand: "Vence Tudo", category: "Condutor", code: "900100070", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-100/1.png" },
  { name: "Condutor longo - 0066001234", brand: "Case", category: "Condutor", code: "0066001234", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-101/1.png" },
  { name: "Condutor de Sementes - Semeato - 28040011", brand: "Semeato", category: "Condutor", code: "28040011", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-102/1.png" },
  { name: "Condutor de adubo - Semeato - 25070017", brand: "Semeato", category: "Condutor", code: "25070017", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-103/1.png" },
  { name: "Condutor de Semente - Semeato - 15230052", brand: "Semeato", category: "Condutor", code: "15230052", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-104/1.png" },
  { name: "Condutor de Semente - Semeato - 25070018", brand: "Semeato", category: "Condutor", code: "25070018", image: "" },
  { name: "Condutor de Sementes - Jumil - 2748209", brand: "Jumil", category: "Condutor", code: "2748209", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-106/1.png" },
  { name: "Condutor Duplo Curto - Semeato - 28160084", brand: "Semeato", category: "Condutor", code: "28160084", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-107/1.png" },
  { name: "Condutor da Semente - 2749448", brand: "Jumil", category: "Condutor", code: "2749448", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-108/1.png" },
  { name: "Condutor de Adubo - Semeato - 28160045", brand: "Semeato", category: "Condutor", code: "28160045", image: "" },
  { name: "Fixador Y - Imasa - 50300000113", brand: "Imasa", category: "Fixador", code: "50300000113", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-110/1.png" },
  { name: "Condutor Prolongador - 15040028", brand: "Semeato", category: "Condutor", code: "15040028", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-111/1.png" },
  { name: "Condutor de Sementes - Vence Tudo - 900100374", brand: "Vence Tudo", category: "Condutor", code: "900100374", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-112/1.png" },
  { name: "Condutor Duplo longo - Semeato - 15160009", brand: "Semeato", category: "Condutor", code: "15160009", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-113/1.png" },
  { name: "Condutor de Sementes - Jumil - 2749448", brand: "Jumil", category: "Condutor", code: "2749448", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-114/1.png" },
  { name: "Condutor de adubo - Juhmil - 2734083", brand: "Jumil", category: "Condutor", code: "2734083", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-115/1.png" },
  { name: "Condutor de Sementes - Semeato -76070032", brand: "Semeato", category: "Condutor", code: "76070032", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-116/1.png" },
  { name: "Condutor de Sementes - 15070029", brand: "Semeato", category: "Condutor", code: "15070029", image: "" },
  { name: "Condutor de Sementes - 28180098", brand: "Semeato", category: "Condutor", code: "28180098", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-118/1.png" },
  { name: "Base Dosador - Semeato -06070059", brand: "Semeato", category: "Base", code: "06070059", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-119/1.png" },
  { name: "Condutor - Vende Tudo - 900100001 - 34350013", brand: "Vence Tudo", category: "Condutor", code: "34350013", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-120/1.png" },
  { name: "Condutor Vence tudo - 90003701 - 900100142", brand: "Vence Tudo", category: "Condutor", code: "900100142", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-121/1.png" },
  { name: "Bocal Reto - Semeato - 26100001", brand: "Semeato", category: "Bocal", code: "26100001", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-122/1.png" },
  { name: "Condutor de sementes - Semeato - 15070066", brand: "Semeato", category: "Condutor", code: "15070066", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-123/1.png" },
  { name: "Base Dosador - Semeato - DI02010001", brand: "Semeato", category: "Base", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-124/1.png" },
  { name: "Base Dosador - Semeato - 06070034", brand: "Semeato", category: "Base", code: "06070034", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-125/1.png" },
  { name: "Condutor de Sementes - YD065907", brand: "Kuhn", category: "Condutor", code: "", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-126/1.png" },
  { name: "Condutor Curvo - Semeato - 26120001", brand: "Semeato", category: "Condutor", code: "26120001", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-127/1.png" },
  { name: "Condutor de Adubo Reto - Semeato - 62010020", brand: "Semeato", category: "Condutor", code: "62010020", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-128/1.png" },
  { name: "Condutor - Vence Tudo - 900100557", brand: "Vence Tudo", category: "Condutor", code: "900100557", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-129/1.png" },
  { name: "Condutor de Adubo - Vence Tudo - 35180006", brand: "Vence Tudo", category: "Condutor", code: "35180006", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-130/1.png" },
  { name: "Condutor curto- AGCO - Massey -  Valtra - 33070004 - 44070009", brand: "AGCO", category: "Condutor", code: "44070009", image: "https://xebskockruobeovmqlhq.supabase.co/storage/v1/object/public/product-images/product-131/1.png" },
]
